language: python
jobs:
  include:
    - name: "Python 3.5 on Linux"
      python: 3.5           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.6 on Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7 on Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.8 on Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

#install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'
# PyPy versions #Disabled due to: legacy 64 byte hex keyfile test | FAIL | OSError: Could not read keyfile
#  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip3 install --upgrade pip
  - pip3 install wheel
  - pip3 install -r requirements.txt
  - pip3 install pylint
  - pip3 install .

#Compile/install test
script:
  - robot tests
      
#deploy:
#  - provider: pypi
#    user: "__token__"
#    password:
#      secure: $PYPI_ORG
#    distributions: "sdist bdist_wheel"
#    skip_existing: true
#    skip_cleanup: true
#    on:
#       repo: loomanw/robotframework-keepasslibrary
#       branch: master
#       python: "3.7"
#       tags: true
#  - provider: pypi
#    user: "__token__"
#    password:
#      secure: $TEST_PYPI_ORG
#    server: https://test.pypi.org/legacy/
#    distributions: "sdist bdist_wheel"
#    skip_existing: true
#    skip_cleanup: true
#    on:
#       repo: loomanw/testtravis
#       branch: master
#       python: "3.7"
#       tags: true